# (Opsiyonal) Olist reviews' - Translations...

* 🇧🇷 Brezilya Portekizcesi bilmiyorsanız, hadi `order_reviews` metinlerini 🇬🇧 İngilizce’ye çevirelim!

* Bunun için `pip install googletrans==4.0.2` yüklemeniz gerekecek.

☢️ Bu API ile herhangi bir sorun yaşarsanız, bunu düzeltmek için zaman harcamayın, bu package oldukça dengesiz… Aklınızda bulunsun:
- bu optional bir challenge
- Brezilya Portekizcesi ile yazılmış review’ların anlamını görmek için bazı yorumları Google Translate’e kopyalayıp yapıştırarak yine de eski yöntemle yapabilirsiniz.

## Review Translator

👉 `reviews` dataset’ini load edin ve 1-yıldız rating’e sahip review’lardan bir örnek (sample) seçin.

In [3]:
# Verileri yükle
from olist.data import Olist
data = Olist().get_data()
reviews = data["order_reviews"]
reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

👀 20 adet düşük puan alan yorumdan oluşan bir örneklem seçin (rastgele) ve bunu bir listeye dönüştürün.

In [30]:
df_new = reviews[reviews["review_score"] == 1]
df_sample = df_new.sample(n=100)
df_sample

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
58475,78a5f0dbe3e4e6c6bece3c3b765fbfac,42c01179f293a47a1986fcc2bf8117ca,1,NaN,Detestei... pro dito de péssima qualidade... b...,2017-10-25 00:00:00,2017-10-25 14:10:06
28031,88e73a14ce451f0e3e5a428eb91ce7a0,c17b02295ec6b4123fc72d0fa23f97d1,1,NaN,NaN,2017-12-01 00:00:00,2017-12-02 14:31:22
26390,67b66d3596fd8bbc89963f9ed262804b,30eb48d11917481e5af28f68d39002e9,1,NaN,Produto veio avariado. \r\nAte o momento não o...,2018-08-08 00:00:00,2018-08-13 11:20:27
19267,abdb5f5966cac2ff528f6b5c75b6afd6,d7de9dbe0c0b04bf4402594c60a4991f,1,NaN,NUNCA MAIS lannister UM ENGODO. vOU DIVULGAR E...,2017-08-03 00:00:00,2017-08-04 01:15:30
21807,082e7b174bb2d222022d8a403da0f399,01d90c5856f7551e108f2a0864ff6e54,1,Pedido errado.,"Meu produto chegou incompleto,faltou um produt...",2018-07-06 00:00:00,2018-07-06 20:15:37
...,...,...,...,...,...,...,...
33346,587688e2683b6b746b4834dc7576263d,6c1798a95735e69db81fe92f8c40bdb4,1,NaN,Não recebi o produto,2017-09-17 00:00:00,2017-09-19 00:06:06
61903,5f7a55171eb2746ba5f8e60c8d7eec1e,992cbe3e064cd39f9ccde60a29ffcd3c,1,NaN,NaN,2018-02-11 00:00:00,2018-02-13 11:50:56
35434,09554f1ed065aff41a46f304965f5e83,3388fa275fc1b344e275af704e8d3156,1,NaN,"Logistica ridicula, so nao cancelei o pedido p...",2017-12-30 00:00:00,2018-01-02 12:59:48
19846,ffa7049224ae75fce308ae1a4aacf1c4,57d94aaa6b72ca15b3e4801c6d5c0959,1,NaN,"Solicitei Toner CB436A e recebi Toner CB435A, ...",2017-08-19 00:00:00,2017-08-21 13:11:31
12698,97dcdbd470c857c72b04aab2db9e7377,15a8702db12279bdbd97a9f39a529bd5,1,Descaso,"Depois de 25 dias esperando pelo meu produto, ...",2018-06-07 00:00:00,2018-06-07 10:53:13

🗣 Bu göreve başlamadan önce önceden yüklediğiniz `google_translator` paketini kullanarak bu yorumları çevirin:

In [21]:
!pip install deep-translator

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/lib/python3.12/site-packages (from deep-translator) (4.13.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/lib/python3.12/site-packages (from deep-translator) (2.32.3)
Requirement already satisfied: soupsieve>1.2 in /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/lib/python3.12/site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/lib/python3.12/site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/lib/python3.12/site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/lib/python3.12/site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/lib/python3.12/site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/lib/python3.12/site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2025.1.31)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4

In [31]:
from deep_translator import GoogleTranslator
import pandas as pd

translator = GoogleTranslator(source='pt', target='en')

def safe_translate(text):
    if pd.isna(text) or str(text).strip() == "":
        return None
    try:
        return translator.translate(str(text))
    except Exception as e:
        print("HATA:", e)
        return None

df_sample["translated_review"] = df_sample["review_comment_message"].apply(safe_translate)
df_sample

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,translated_review
58475,78a5f0dbe3e4e6c6bece3c3b765fbfac,42c01179f293a47a1986fcc2bf8117ca,1,NaN,Detestei... pro dito de péssima qualidade... b...,2017-10-25 00:00:00,2017-10-25 14:10:06,I hated it... probably poor quality... super s...
28031,88e73a14ce451f0e3e5a428eb91ce7a0,c17b02295ec6b4123fc72d0fa23f97d1,1,NaN,NaN,2017-12-01 00:00:00,2017-12-02 14:31:22,None
26390,67b66d3596fd8bbc89963f9ed262804b,30eb48d11917481e5af28f68d39002e9,1,NaN,Produto veio avariado. \r\nAte o momento não o...,2018-08-08 00:00:00,2018-08-13 11:20:27,"Product arrived damaged. \r\nTo date, I have n..."
19267,abdb5f5966cac2ff528f6b5c75b6afd6,d7de9dbe0c0b04bf4402594c60a4991f,1,NaN,NUNCA MAIS lannister UM ENGODO. vOU DIVULGAR E...,2017-08-03 00:00:00,2017-08-04 01:15:30,NEVER AGAIN Lannister A DECEIT. I WILL DISCLOS...
21807,082e7b174bb2d222022d8a403da0f399,01d90c5856f7551e108f2a0864ff6e54,1,Pedido errado.,"Meu produto chegou incompleto,faltou um produt...",2018-07-06 00:00:00,2018-07-06 20:15:37,"My product arrived incomplete, one product was..."
...,...,...,...,...,...,...,...,...
33346,587688e2683b6b746b4834dc7576263d,6c1798a95735e69db81fe92f8c40bdb4,1,NaN,Não recebi o produto,2017-09-17 00:00:00,2017-09-19 00:06:06,I didn't receive the product
61903,5f7a55171eb2746ba5f8e60c8d7eec1e,992cbe3e064cd39f9ccde60a29ffcd3c,1,NaN,NaN,2018-02-11 00:00:00,2018-02-13 11:50:56,None
35434,09554f1ed065aff41a46f304965f5e83,3388fa275fc1b344e275af704e8d3156,1,NaN,"Logistica ridicula, so nao cancelei o pedido p...",2017-12-30 00:00:00,2018-01-02 12:59:48,"Ridiculous logistics, I just didn't cancel the..."
19846,ffa7049224ae75fce308ae1a4aacf1c4,57d94aaa6b72ca15b3e4801c6d5c0959,1,NaN,"Solicitei Toner CB436A e recebi Toner CB435A, ...",2017-08-19 00:00:00,2017-08-21 13:11:31,I requested Toner CB436A and received Toner CB...
12698,97dcdbd470c857c72b04aab2db9e7377,15a8702db12279bdbd97a9f39a529bd5,1,Descaso,"Depois de 25 dias esperando pelo meu produto, ...",2018-06-07 00:00:00,2018-06-07 10:53:13,"After waiting for my product for 25 days, I wa..."

**Insights** 💡
- Bazı kötü review’lar delivery ile ilgili (`wait_time`, kaçırılan teslim tarihi, vb.)
- Ancak bazı kötü review’lar seller veya ürünle ilgili...

Peki iki olası nedeni nasıl ayırt edebiliriz?

Bu Olist’in mutlaka bilmesi gereken bir şey:
- bazı ürünleri katalogdan mı çıkarmalı?
- yoksa bazı seller’ları marketplace’ten mi kaldırmalı?

In [37]:
def categorize(text):
    if text is None:
        return "Other"
    
    text = text.lower()

    if "delay" in text or "late" in text:
        return "Delivery Issue"
    elif "broken" in text or "damaged" in text:
        return "Damaged Product"
    elif "wrong" in text:
        return "Wrong Item"
    elif "refund" in text:
        return "Refund Issue"
    else:
        return "Other"

In [38]:
df_sample["theme"] = df_sample["translated_review"].apply(categorize)
df_sample["theme"].value_counts(normalize=True) * 100

theme
Other              93.0
Delivery Issue      4.0
Wrong Item          2.0
Damaged Product     1.0
Name: proportion, dtype: float64